### ISSUE TITLE
Issue old illumina encoding in s01_PrepareFastQ protocol

### ISSUE THREAD

**Issue by BenjaminsM** [molgenis/NGS_DNA#187]
When Illumina encoding ==1.9 there is an issue with zipping the fastq file:
This is caused by the mkfifo command, this can be solved by not using this command but to do the encoding and zipping seperatly

example:
else
                #make fastQ out of the fq.gz file
                #mkfifo "${barcodeFqGz}.encoded.fq"
                echo "converting Illumina encoding"
                seqtk seq "${barcodeFqGz}" -Q 64 -V > "${barcodeFqGz}".encoded.fq

                echo -e "done..\nNow gzipping ${barcodeFqGz}.encoded.fq > ${barcodeFinalFqGz}"
                pigz -c "${barcodeFqGz}.encoded.fq" > "${barcodeFinalFqGz}"

**Comment by RoanKanninga** [comment]
fixed
