### ISSUE TITLE
moving emit_conf and call_conf to VariantGenotyping 

### ISSUE THREAD

**Issue by RoanKanninga** [molgenis/NGS_DNA#74]
removing unused parameters in VariantCalling protocol
 -stand_call_conf 10.0 
 -stand_emit_conf 20.0 

Add to VariantGenotyping
 -stand_call_conf 10 
 -stand_emit_conf 30

**Comment by mmterpstra** [comment]
@RoanKanninga @Gerbenvandervries @freerkvandijk 
A better idea is to output a rawish (.raw.vcf) file with the filtered variants in it if people want to go deep in the sequencing output. In this way this will be less disruptive to the status quo.
